# action.yml
name: 'Testim CLI'
description: 'Run tests on Testim.io'
inputs:
  token:  # id of input
    description: 'Testim auth token'
    required: true
  project:
    description: 'Project ID'
    required: true
  grid:
    description: 'Grid to run the tests on'
    required: false
    default: "Testim-Grid"
  suite:
    description: 'The test suite to execute'
    required: false
  base-url:
    description: 'The URL of the app to test'
    required: false
  retries:
    description: 'When this flag is used, a failed test will be executed repeatedly until either the test passes or the max number of retries has been reached - in which case the test will fail'
    required: false
    default: '1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.project }}
    - ${{ inputs.grid }}
    - ${{ inputs.base-url }}
    - ${{ inputs.retries }}
    - ${{ inputs.suite }}
